## Introducing ```numpy``` and arrays

To begin processing image data, we need to understand what's going on behind the scenes.

We can do that using a library called ```numpy```, which stands for __Numerical Python__. 

In general, you should use this library when you want to do fancy mathemtical operations with numbers, especially if you have arrays or matrices.

In [1]:
# tools for interacting with the operating system
import os

# tool fo working with arrays
# creating an abbreviation to save keystrokes
import numpy as np

In [8]:
# load data
# path from relative = ../data/sample-data
# path from nowhere = /Users/oliverkjoeller/Desktop/visual_analytics/cds-visual/data/sample-data
filepath = '../data/sample-data/sample-data-01.csv'

In [9]:
# show array
np.loadtxt(fname=filepath,
            delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

The expression ```numpy.loadtxt(...)``` is a function call that asks Python to run the function ```loadtxt``` which belongs to the ```numpy``` library. This dotted notation is used everywhere in Python: the thing that appears before the dot contains the thing that appears after.


```numpy.loadtxt``` has two parameters: the name of the file we want to read and the delimiter that separates values on a line. These both need to be character strings (or strings for short), so we put them in quotes.

__Assign to variable__

In [15]:
# load array
data = np.loadtxt(fname=filepath,
                delimiter=",")

In [17]:
# inspect array
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [18]:
# print data type
print(type(data))

<class 'numpy.ndarray'>


__numpy.ndarray__ tells us that we are working with an N-dimensional array

In this case, it's 2-dimensional

In [19]:
# print type of data points (the data of individual points of the array)
print(data.dtype)

float64


In [20]:
# print shape
print(data.shape)

(60, 40)


In [21]:
# check shape
print(60*40)

2400


__Index__

Indexing is similar to lists and strings, but we need to inlcude both row and column

In [25]:
test = "this is my string"
print(test[9])

y


In [24]:
first_value = data [0,0]
print(first_value)

0.0


__Question:__ What is the middle value of the array?

In [26]:
# your code here
middle_value = data[30,20]


Print the value of ```middle_value``` to the screen:

In [27]:
# your code here
print(middle_value)

13.0


<img src="../data/viz/python-zero-index.svg">

__Slice__

An index like [30, 20] selects a single element of an array, but we can select whole sections as well. 

For example, we can select the first ten columns of values for the first four rows like this:

In [31]:
print(data[0:4,0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


First ten columns, rows five-ten

In [32]:
print(data[4:10,0:10])

[[0. 1. 1. 3. 3. 1. 3. 5. 2. 4.]
 [0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


__Select only one row__

In [36]:
# your code here
print(data[0,:])

[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]


__Select only one column__

In [35]:
# your code here
print(data[:,0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


__Numpy functions__

```numpy``` comes with a range of built-in methods which allow you to quickly and efficiently calculate descriptive statistics for an array.

In [37]:
# your code here
print(np.mean(data))

6.14875


In [38]:
# your code here
print(np.max(data))

20.0


In [39]:
# your code here
print(np.std(data))

4.613833197118566


In [41]:
mean_value, max_value, min_value = np.mean(data), np.max(data), np.min(data)
print(mean_value, max_value, min_value)

6.14875 20.0 0.0


Show numpy + dot + tab, access full range of options. Show ```help()```

In [ ]:
# your code here

__Operation across rows__

In [ ]:
# your code here

In [ ]:
# your code here

"Average score per day"

__Operation along columns__

"Average score per patient"

<img src="../data/viz/numpy-axes.png">

In [ ]:
# your code here

In [ ]:
# your code here

This is a good overview to show how things work wiht ```numpy```:

https://www.sharpsightlabs.com/blog/numpy-axes-explained/

## Exercise

- We saw how to calculate descriptive statistics for a single array. In the data folder, there are more examples of sample data in the folder called [data/sample-data]("../data/sample-data").
  - Write some code which does the following steps:
    - Load every CSV data file in the input folder one at a time
    - For each CSV file, calculate: 
      - The mean and median values for each patient
        - Create a list of tuples for each CSV 
          - Eg: [(```patient0_mean, patient0_median```),
                 (```patient1_mean, patient1_median```),
                 etc, etc]
      - The same as above, but this time calculating the mean, median, and modal values for each day
       

## Basic image processing with OpenCV

We start by loading all of the modules we'll need for this class

In [ ]:
# We need to incldue the home directory in our path, so we can read in our own module.
import sys
sys.path.append("..")

In [ ]:
# python framework for working with images
import cv2

# some utility functions for plotting images
from utils.imutils import jimshow

__Read image__

We can load an image using a handy function from OpenCV

In [ ]:
# your code here

In [ ]:
# your code here

In [ ]:
# your code here

__Save image__

In [ ]:
# your code here

In [ ]:
# your code here

In [ ]:
# your code here

__Inspect image__

In [ ]:
# your code here

In [ ]:
# your code here

## What is an image?

__Remember how ```numpy``` arrays work!__

ROWSxCOLUMNS == HEIGHTxWIDTH

In [ ]:
# your code here

In [ ]:
# your code here

In our image, there are 228*350 = 79,800 pixels

__What about the last one?__

In [ ]:
# your code here

<img src="../data/viz/3-channels.png">

__NB!__

```OpenCV``` stores RGB tuples in REVERSE ORDER

__What colour is a specific pixel?__

In [ ]:
# your code here

In [ ]:
print(f"[INFO] pixels at (0, 0) - Red: {r}, Green {g}, Blue: {b}")

__Modify colour__

In [ ]:
# your code here

In [ ]:
print(f"[INFO] pixels at (0, 0) - Red: {r}, Green {g}, Blue: {b}")

__Image slice__

In [ ]:
# your code here

In [ ]:
# your code here

__Change corner colour__

In [ ]:
# your code here

In [ ]:
# your code here